strategy: SimpleLinearScalingInStrategy
cash: 5000.00
symbols:
  - USDCAD Curncy
root_multiplier:
benchmark: USDCAD Curncy           # or leave it empty
start_date: 2015-01-01
end_date: 2017-05-01
params:
  lookback_window: 200
datasource: local   # local, multi_local, quandl, tushare
hist_dir: d:/workspace/elitequant_python/hist/
output_dir: d:/workspace/elitequant_python/out/
fvp_file:           # FUT_VAL_PT, for example stocks = 1; CLA Comdty is 1000
#---- used by optimization engine ----------#
batch_tag:
params_list: